### PR TITLE
NIP-77: expressing trust relationships

### PR DESCRIPTION
**Pull request by lez**
Discussed in https://github.com/nostr-protocol/nips/pull/1208 May/Jun 2024

I want to leave it here for its simplicity and conscise format. My takeaway from this PR was that trust is something that people think about in 1000 different ways. For ongoing applications, see the projects of participants in the discussion.
David, Franzap, Arthurfranca and others.

And remember. Trust, but verify!
(by Greg <five@satshoot.com>)

### CODE REVIEW

**Comment by arthurfranca** [comment]
Sorry I wasn't clear on the readme, the intention is to group some nip ideas from myself only.

I would be happy to add your repo to the heretical specs list if you create one, like the BUDs and DIPs.

**Comment by arthurfranca** [comment]
I will add your https://github.com/lez/anips repo to the readme list in the meantime.

**Comment by lez** [comment]
I dodn't plan to maintain such a repo, but now I think I will.
https://github.com/lez/nipls

**Comment by arthurfranca** [comment]
Nice! Added to the list

**Pull request closed without merging**
